### ISSUE TITLE
Some models can not be downloaded ｜ 一些模型失效了

### ISSUE THREAD

**Issue by liangliangdeveloper** [ShuhongChen/animerecon-benchmark#1]
Some models can not be downloaded, the page shows "ページが見つかりません"(The Page is not Found)
The url is https://3d.nicovideo.jp/works/td63626

一些模型没有办法被下载了，打开页面后不存在，应该是被删除了，作者可以更新一下
url是https://3d.nicovideo.jp/works/td63626

Thanks for your work
感谢你们的工作，对我很有启发，最近也在尝试复现，希望有更多交流

**Comment by ShuhongChen** [comment]
It seems yozora mel's model was taken down after she was terminated...

I found someone uploaded hololive models here, mel's is there too: https://drive.google.com/drive/folders/1XdpHfwwIpfUP1oq3l7H2pv_vJXME9_4w?usp=sharing
